server:
  port: 8201

spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider
  registry:
    protocol: zookeeper
    address: zookeeper://10.0.0.101:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.chtiucao.dubbo.provider.service.impl


